Algoritmo "DepositoSaldoAtual"


Var saldo, deposito, saldoAtual: REAL

Inicio
      escreva("Qual é o seu saldo da conta: R$")
      leia(saldo)
      escreval("Qual é o valor de depósito: R$")
      leia(deposito)
      saldoAtual<-saldo+deposito
      escreval("Seu saldo inicial era de: R$", saldo)
      escreval("O valor de depósito foi: R$", deposito)
      escreval("Seu saldo atual é de: R$", saldoAtual)



Fimalgoritmo